apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets/helmrepository.yaml
  - sealed-secrets/helmrelease.yaml
  - vault/namespace.yaml
  - vault/helmrepository.yaml
  - vault/entrypoint-configmap.yaml
  - vault/values.yaml
  - vault/helmrelease.yaml
  - vault/serverstransport.yaml
  - vault/setup-job.yaml
  - zitadel/namespace.yaml
  - zitadel/helmrepository.yaml
  - zitadel/values.yaml
  - zitadel/helmrelease.yaml
