apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vault/namespace.yaml
  - vault/serviceaccount.yaml
  - vault/helmrepository.yaml
  - vault/values.yaml
  - vault/helmrelease.yaml
  - vault/serverstransport.yaml
  - vault/init-job.yaml
  - vault/setup-job.yaml
  - zitadel/namespace.yaml
  - zitadel/serviceaccount.yaml
  - zitadel/helmrepository.yaml
  - zitadel/values.yaml
  - zitadel/helmrelease.yaml