apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-init
  namespace: zitadel
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-init
  namespace: zitadel
subjects:
  - kind: ServiceAccount
    name: vault-init
    namespace: vault
roleRef:
  kind: Role
  name: vault-init
  apiGroup: rbac.authorization.k8s.io