apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
  install:
    strategy:
      name: RetryOnFailure # retry failed installations instead of uninstalling
      retryInterval: 5m # retry failed installations every five minutes
  upgrade:
    crds: CreateReplace # update CRDs when upgrading
    strategy:
      name: RetryOnFailure # retry failed upgrades instead of rollback
      retryInterval: 5m # retry failed upgrades every five minutes
  # All ConfigMaps and Secrets referenced in valuesFrom should
  # be labelled with `reconcile.fluxcd.io/watch: Enabled`
  valuesFrom:
    - kind: ConfigMap
      name: vault-values