apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-values
  namespace: vault
  labels:
    reconcile.fluxcd.io/watch: Enabled
data:
  values.yaml: |
    global:
      enabled: true

    injector:
      enabled: true

    server:
      image:
        repository: hashicorp/vault
        tag: latest

      serviceAccount:
        create: false
        name: vault-init
        
      readinessProbe:
        enabled: true

      livenessProbe:
        enabled: true
        execCommand:
          - /bin/sh
          - -ec
          - vault status -tls-skip-verify
        initialDelaySeconds: 60

      dataStorage:
        enabled: true
        size: 1Gi
        storageClass: local-path

      volumes:
        - name: vault-secrets
          hostPath:
            path: /opt/vault/secrets
            type: DirectoryOrCreate

      volumeMounts:
        - name: vault-secrets
          mountPath: /vault/secrets

      standalone:
        enabled: true
        config: |
          ui = true

          listener "tcp" {
            address         = "[::]:8200"
            cluster_address = "[::]:8201"
            tls_disable     = 1
          }

          storage "file" {
            path = "/vault/data"
          }

      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: vault.local
            paths:
              - /
        tls:
          - hosts:
              - vault.local

    ui:
      enabled: true
      serviceType: ClusterIP